[project]
name = "reefer"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
ipykernel = ">=6.29.5,<6.30"
requests = ">=2.32.3,<2.33"
setuptools = ">=72.1.0,<72.2"
anthropic = ">=0.34.0,<0.35"
linkedin-api = ">=2.3.0,<3"

[pypi-dependencies]
undetected-chromedriver = "*"
selenium = "*"
beautifulsoup4 = "*"
python-fasthtml = ">=0.5.1, <0.6"
